apiVersion: apps/v1
kind: Deployment
metadata:
  name: neos-hdl-users-2-discord
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neos-hdl-users-2-discord
    spec:
      containers:
      - name: neos-hdl-users-2-discord
        image: ghcr.io/totegamma/neoshdlusers2discord:master
        envFrom:
          - secretRef:
              name: nhu2d-secrets

