apiVersion: apps/v1
kind: Deployment
metadata:
  name: neos-hdl-users-2-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      name: neos-hdl-users-2-discord
  template:
    metadata:
      labels:
        name: neos-hdl-users-2-discord
    spec:
      containers:
      - name: neos-hdl-users-2-discord
        image: ghcr.io/totegamma/neoshdlusers2discord:master
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: nhu2d-secrets
        livenessProbe:
          exec:
            command:
              - rm
              - /tmp/healthy
          initialDelaySeconds: 30
          periodSeconds: 120

